version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_dbkomal
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: Myuser@1234
    ports:
      - "3310:3310"
    command: --port=3310  # Force MySQL to run on 3310

    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build: .
    container_name: django_blogkomal
    restart: always
    depends_on:
      - db
    environment:
      - DEBUG=True
      - DATABASE_NAME=mydatabase
      - DATABASE_USER=myuser
      - DATABASE_PASSWORD=Myuser@1234
      - DATABASE_HOST=db
      - DATABASE_PORT=3310
    ports:
      - "8003:8003"
    volumes:
      - .:/app

volumes:
  mysql_data:
