version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: blogspot_db
      MYSQL_USER: bloguser
      MYSQL_PASSWORD: blogpassword
    ports:
      - "3310:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build: .
    container_name: django_blog
    restart: always
    depends_on:
      - db
    environment:
      - DEBUG=True
      - DATABASE_NAME=mydatabase
      - DATABASE_USER=myuser
      - DATABASE_PASSWORD=Myuser@1234
      - DATABASE_HOST=localhost
      - DATABASE_PORT=3306
    ports:
      - "8003:8003"
    volumes:
      - .:/app

volumes:
  mysql_data:
